version: '3.5'

services:
  database:
    container_name: cloud-parking
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: parking
      PGDATA: /data/parking
    volumes:
      - cloud-parking:/data/parking
    ports:
      - "5432:5432"

volumes:
  cloud-parking: